#!/bin/bash -e
#
# Apply migrations with `alembic`.


if [ -d '.venv' ] ; then
    PREFIX='.venv/bin/'
else
    PREFIX=''
fi

if [ -n "$1" ]
then
    [ "$1" -gt 0 ] && UPGRADE_TO="+$1" || UPGRADE_TO="$1"
else
    UPGRADE_TO='head'
fi

${PREFIX}alembic upgrade "${UPGRADE_TO}"
