version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '17:00'
    groups:
      all-actions:
        patterns: ['*']
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '17:00'
    groups:
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      prod-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
