version: "3.9"
services:
  postgres:
    container_name: clairbuoyant-postgres
    image: postgis/postgis
    restart: always
    networks:
      dev:
        aliases:
          - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-clairbuoyant}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  redis:
    container_name: clairbuoyant-redis
    image: redis
    restart: always
    networks:
      dev:
        aliases:
          - redis
    ports:
      - 6379:6379

volumes:
  db-data:

networks:
  dev:
