[tool.poetry]
name = "clair-buoyant_server"
version = "0.1.0"
description = "clairBuoyant Server"
authors = ["Kyle J. Burda <47502769+kylejb@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.70.0"
requests = "^2.26.0"
uvicorn = "^0.16.0"
GeoAlchemy2 = "^0.10.0"
alembic = "^1.7.5"
python-dotenv = "^0.19.2"
asyncpg = "^0.25.0"
SQLAlchemy = "^1.4.29"
greenlet = "^1.1.2"

[tool.poetry.dev-dependencies]
pydantic = "^1.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
