[tool.poetry]
name = "clair-buoyant_server"
version = "0.1.0"
description = "clairBuoyant Server"
authors = ["Kyle J. Burda <47502769+kylejb@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.70.0"
psycopg2 = "^2.9.1"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
uvicorn = "^0.15.0"
pydantic = "^1.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
