[tool.poetry]
name = "clair-buoyant_server"
version = "0.1.0"
description = "clairBuoyant Server"
authors = ["Kyle J. Burda <47502769+kylejb@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
fastapi = "^0.75.2"
requests = "^2.27.1"
uvicorn = "^0.17.6"
pydantic = "^1.9.1"
GeoAlchemy2 = "^0.11.1"
alembic = "^1.7.7"
python-dotenv = "^0.20.0"
asyncpg = "^0.25.0"
SQLAlchemy = "^1.4.36"
greenlet = "^1.1.2"
beautifulsoup4 = "^4.11.1"
lxml = "^4.8.0"

[tool.poetry.dev-dependencies]
black="^22.3.0"
coverage = { version = "6.3.2", extras = ["toml"]}
isort = { version = "^5.10.1", extras = ["pyproject"]}
pytest="^7.1.2"

[tool.black]
# https://github.com/psf/black
line-length = 88
target_version = ['py310']
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | venv
    | .venv
  )/
)
'''

[tool.isort]
# https://github.com/timothycrosley/isort
# https://github.com/timothycrosley/isort/wiki/isort-Settings
line_length = 88
indent = '    '
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0


[tool.coverage]
# https://github.com/nedbat/coveragepy
  [tool.coverage.run]

  source = ["server"]
  branch = true
  omit = ['']

  [tool.coverage.report]
  exclude_lines = [
    "# noqa",
    "raise NotImplementedError"
  ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
