[tool.poetry]
name = "server"
version = "0.1.2"
description = "clairBuoyant Server"
authors = ["Kyle J. Burda <47502769+kylejb@users.noreply.github.com>"]

[tool.poetry.dependencies]
alembic = "^1.12.0"
asyncpg = "^0.28.0"
fastapi = "^0.104.0"
GeoAlchemy2 = "^0.14.1"
greenlet = "^3.0.0"
gunicorn = "^21.2.0"
pybuoy = "^0.5.2"
pydantic = "^2.4.2"
pydantic-settings = "^2.0.3"
python = ">=3.11, <4.0"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
Shapely = "^2.0.2"
SQLAlchemy = "^2.0.22"
uvicorn = "^0.23.2"

[tool.poetry.dev-dependencies]
black="^23.10.0"
coverage = { version = "7.3.2", extras = ["toml"]}
flake8 = "^6.1.0"
httpx = "^0.25.0"
isort = { version = "^5.12.0", extras = ["pyproject"]}
mypy = "^1.6.1"
pre-commit = "^3.5.0"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"
pytest="^7.4.2"

[tool.poetry.scripts]
bootstrap="scripts.poetry_entrypoint:bootstrap"
check="scripts.poetry_entrypoint:check"
clean="scripts.poetry_entrypoint:clean"
coverage="scripts.poetry_entrypoint:coverage"
db-create="scripts.poetry_entrypoint:create"
db-docker="scripts.poetry_entrypoint:docker"
db-migrations_autogenerate="scripts.poetry_entrypoint:migrations_autogenerate"
db-migrations_run="scripts.poetry_entrypoint:migrations_run"
db-migrations_undo="scripts.poetry_entrypoint:migrations_undo"
db-seeds="scripts.poetry_entrypoint:seeds"
dotenv="scripts.poetry_entrypoint:dotenv"
init="scripts.poetry_entrypoint:init"
lint="scripts.poetry_entrypoint:lint"
setup="scripts.poetry_entrypoint:setup"
start="scripts.poetry_entrypoint:start"
test="scripts.poetry_entrypoint:test"
uninstall="scripts.poetry_entrypoint:uninstall"

[tool.black]
# https://github.com/psf/black
line-length = 88
target_version = ['py310']
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | venv
    | .venv
  )/
)
'''

[tool.coverage]
# https://github.com/nedbat/coveragepy
  [tool.coverage.run]

  source = ["server"]
  branch = true
  omit = ['']

  [tool.coverage.report]
  exclude_lines = [
    "# noqa",
    "# pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == \"__main__\":",
  ]

[tool.isort]
profile="black"

[tool.mypy]
explicit_package_bases = true
namespace_packages = true

[tool.pytest.ini_options]
asyncio_mode = "strict"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
