#!/bin/bash -e
#
# SETUP
# Installs application dependencies.
#

# Install dependencies
poetry install

# Install githooks with pre-commit
command -v pre-commit &> /dev/null && pre-commit install --hook-type commit-msg || echo >&2 "pre-commit not found."
