#!/bin/sh -e

# LOAD ENV VARIABLES
# TODO: confirm server runs dev/prod based on env
if [ -f .env ]; then
  export $(echo $(cat .env | sed 's/#.*//g'| xargs) | envsubst)
fi

if [ -d '.venv' ] ; then
    PREFIX=".venv/bin/"
else
    PREFIX=""
fi
${PREFIX}python server/main.py
