#!/bin/bash -e
#
# Start server locally.

# CURRENT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# BASE_DIR="$(dirname "$CURRENT_DIR")"

# LOAD ENV VARIABLES
# source ${BASE_DIR}/scripts/dotenv
# load_env

if [ -d '.venv' ] ; then
    PREFIX=".venv/bin/"
else
    PREFIX=""
fi
# TODO: server runs dev/prod based on env
${PREFIX}python server/main.py
