#!/bin/sh -e

if [ -d '.venv' ] ; then
    PREFIX=".venv/bin/"
else
    PREFIX=""
fi

if [ -z $GITHUB_ACTIONS ]; then
    scripts/check
fi

${PREFIX}coverage run --concurrency=thread,greenlet -m pytest $@

if [ -z $GITHUB_ACTIONS ]; then
    scripts/coverage
fi
